[WIP]Address changed file path in new version of Kantra
konveyor-ecosystem/kai-vscode-plugin pull request #9
Opened 2024-04-30 13:49 UTC by hhpatel14

2024-04-30 23:09 UTC, jwmatthews commented
Intended to Fix #7

2024-05-03 13:28 UTC, pranavgaikwad approved these changes

2024-05-03 17:04 UTC, pranavgaikwad requested changes

2024-05-03 17:04 UTC, pranavgaikwad commented on src/server/analyzerModel.ts
> +        return 'file:///opt/input/';
I think you need `/opt/input/source`

2024-05-03 17:07 UTC, pranavgaikwad commented on src/server/analyzerModel.ts
> +        return 'file:///opt/input/';
```suggestion
        return 'file:///opt/input/source/';
```

2024-05-08 05:00 UTC, merged